console.log("hola mundo");
a = 2;
b = 3;
console.log(a + b);

const loteria = Math.random() * 100;
console.log(loteria);
console.log(3 + 3);
const perros = [
  {
    nombre: "Rocky",
    raza: "Labrador Retriever",
    edad: 3,
    colorDePelo: "Negro",
    nombrePropietario: "Juan",
    sexo: "Macho",
  },
  {
    nombre: "Luna",
    raza: "Golden Retriever",
    edad: 2,
    colorDePelo: "Dorado",
    nombrePropietario: "María",
    sexo: "Hembra",
  },
  {
    nombre: "Max",
    raza: "Poodle",
    edad: 5,
    colorDePelo: "Blanco",
    nombrePropietario: "Carlos",
    sexo: "Macho",
  },
  {
    nombre: "Coco",
    raza: "Chihuahua",
    edad: 1,
    colorDePelo: "Marrón",
    nombrePropietario: "Laura",
    sexo: "Hembra",
  },
  {
    nombre: "Buddy",
    raza: "Beagle",
    edad: 4,
    colorDePelo: "Tricolor",
    nombrePropietario: "Pedro",
    sexo: "Macho",
  },
  {
    nombre: "Daisy",
    raza: "Bulldog Francés",
    edad: 2,
    colorDePelo: "Blanco y marrón",
    nombrePropietario: "Ana",
    sexo: "Hembra",
  },
  {
    nombre: "Thor",
    raza: "Rottweiler",
    edad: 3,
    colorDePelo: "Negro y marrón",
    nombrePropietario: "Roberto",
    sexo: "Macho",
  },
  {
    nombre: "Bella",
    raza: "Schnauzer",
    edad: 2,
    colorDePelo: "Gris",
    nombrePropietario: "Isabel",
    sexo: "Hembra",
  },
  {
    nombre: "Rocky",
    raza: "Bóxer",
    edad: 4,
    colorDePelo: "Marrón",
    nombrePropietario: "David",
    sexo: "Macho",
  },
  {
    nombre: "Lola",
    raza: "Dachshund",
    edad: 3,
    colorDePelo: "Negro y marrón",
    nombrePropietario: "Patricia",
    sexo: "Hembra",
  },
  {
    nombre: "Toby",
    raza: "Border Collie",
    edad: 1,
    colorDePelo: "Negro y blanco",
    nombrePropietario: "Ricardo",
    sexo: "Macho",
  },
  {
    nombre: "Molly",
    raza: "Shih Tzu",
    edad: 2,
    colorDePelo: "Blanco y marrón",
    nombrePropietario: "Camila",
    sexo: "Hembra",
  },
  {
    nombre: "Simba",
    raza: "Husky Siberiano",
    edad: 3,
    colorDePelo: "Gris y blanco",
    nombrePropietario: "Felipe",
    sexo: "Macho",
  },
  {
    nombre: "Nina",
    raza: "Bichón Maltés",
    edad: 4,
    colorDePelo: "Blanco",
    nombrePropietario: "Sofía",
    sexo: "Hembra",
  },
  {
    nombre: "Oso",
    raza: "San Bernardo",
    edad: 5,
    colorDePelo: "Marrón y blanco",
    nombrePropietario: "Andrés",
    sexo: "Macho",
  },
  {
    nombre: "Mia",
    raza: "Pomerania",
    edad: 2,
    colorDePelo: "Naranja",
    nombrePropietario: "Valentina",
    sexo: "Hembra",
  },
  {
    nombre: "Zeus",
    raza: "Pastor Alemán",
    edad: 3,
    colorDePelo: "Negro y marrón",
    nombrePropietario: "Héctor",
    sexo: "Macho",
  },
  {
    nombre: "Dulce",
    raza: "Yorkshire Terrier",
    edad: 1,
    colorDePelo: "Gris y dorado",
    nombrePropietario: "Monica",
    sexo: "Hembra",
  },
  {
    nombre: "Bruno",
    raza: "Bulldog Inglés",
    edad: 4,
    colorDePelo: "Marrón y blanco",
    nombrePropietario: "Jorge",
    sexo: "Macho",
  },
  {
    nombre: "Dama",
    raza: "Cocker Spaniel",
    edad: 3,
    colorDePelo: "Negro y dorado",
    nombrePropietario: "Lucía",
    sexo: "Hembra",
  },
  {
    nombre: "Rocky",
    raza: "Labrador Retriever",
    edad: 2,
    colorDePelo: "Amarillo",
    nombrePropietario: "Diego",
    sexo: "Macho",
  },
];

// Imprimir el array de perros en la consola
console.log(perros);
